### ISSUE TITLE
Problem with generalize in ./theories/FSets/FMapAVL.v

### ISSUE THREAD

**Issue by wilbowma** [ionathanch/coq#2]
```
File "./theories/FSets/FMapAVL.v", line 1277, characters 1-155:
Error: Abstracting over the term "remove_min l2 x2 d2 r2" leads to a term
fun p : t elt * (key * elt) =>
find y (Node l2 x2 d2 r2 _x4) =
match X.compare y (p#2)#1 with
| LT _ => None
| EQ _ => Some (p#2)#2
| GT _ => find y p#1
end ->
(forall y0 : key,
 In y0 (Node l2 x2 d2 r2 _x4) <-> X.eq y0 (p#2)#1 \/ In y0 p#1) ->
bst p#1 ->
gt_tree (p#2)#1 p#1 ->
find y (join m1 xd#1 xd#2 m2') =
match find y (Node l2 x2 d2 r2 _x4) with
| Some d => Some d
| None => find y m1
end
which is ill-typed.
Reason is: Incorrect elimination of "X.compare y (p#2)#1"
           in the inductive type "Compare":
ill-formed elimination predicate.

make[1]: *** [theories/FSets/FMapAVL.vo] Error 1
```

Look like this errors comes from a unification error during pretyping, as a
result of generalization.
The term is apparently well typed when I type it in at the top level.

It looks like the unification procedure that might raise the error takes an
expected type, so it's possible that while the term is well typed, it's well
typed at a different type than expected.

This seems unlikely given the explanation in the error message is about
"x.Compare y".
It seems more likely that something in inductive types has changed causing
problems in pretyping.

**Comment by ionathanch** [comment]
Fixed by commit 1db88c84275c80ce2a182bf8c351afc58a92534d.
