### ISSUE TITLE
Performance issues causing CI builds to fail

### ISSUE THREAD

**Issue by ionathanch** [ionathanch/coq#5]
[This](https://gitlab.com/ionathanch/coq/pipelines/149568693) pipeline, for instance, fails because it runs out of memory/time trying to compile parts of the standard library. Known culprits include:

* ~`theories/Init/Byte.v`~
* ~`theories/Strings/Byte.v`~
* `theories/setoid_ring/Field_theory.v`

The performance hit may be caused by the extra checks in `Typeops.execute`, in particular for fixpoints, and possibly due to all the reductions that are done for fixpoint types.

EDIT: The reduction of fixpoint types should only be done once per fixpoint right now. Maybe #7 has something to do with this.

**Comment by ionathanch** [comment]
Some profiling data for `theories/Init/Byte.v`:

```
Function name             Own time Tot. time  Own alloc Tot. alloc     Calls 
execute                      7.31     10.84  787131686  936866856    269  19523
type_of_case                 2.46      2.46  146033098  146033098    387      0
type_of_inductive            0.64      0.64    1854318    1854318  10657      0
stage_vars_in_constant       0.43      0.43       1034       1034    517      0
stage_vars_in_relative       0.08      0.08          0          0   2191      0
check_cast                   0.07      0.07         92         92      4      0
check_fixpoint               0.00      0.00          0          0      0      0
get_vstar_vneq               0.00      0.00          0          0      0      0
stage_vars_in_variable       0.00      0.00          0          0      0      0
type_of_inductive_knowing_parameters     -0.05     -0.05    1846720    1846720   5771      0
others                       4.49     15.39 1164861938 2101728886         19796
Est. overhead/total          0.97     16.36    1936741 2103665627
Time in seconds and allocation in words (1 word = 8 bytes)
```

**Comment by ionathanch** [comment]
Looks like a lot of the performance issues come from how constraints are combined. `Constraints.union` creates a new graph and adds every edge in the list of graphs to it, which is inefficient. Maybe we could collect all the edges in a `Set`, then transform the set into a graph when needed.

**Comment by wilbowma** [comment]
Are you reusing some existing representation for constraints? I know Coq must have one for, e.g., unification constraints in type inference.

**Comment by ionathanch** [comment]
No, I'm using a simple `Set` on `int * int * int` (during constraint collection), and later (during actual cycle checking) a graph implementation I lifted from `ocamlgraph`. I'll look into what Coq uses for type constraints, but I don't think anything existing will be exactly what I need, since I need a graph that's both weighted and directed. Universe levels, for instance, use only an acyclic graph (no weights), but that graph module seems pretty coupled with universes, rather than being a general-purpose graph.

**Comment by wilbowma** [comment]
Right. I think we might have talked about this in a meeting sometime and I forgot. Still might be worth seeing if there's a pattern to abstract/steal from what Coq already does. I imagine they've tried to optimize it.

**Comment by ionathanch** [comment]
69643cf21dbf46078f0901cd65f50c3b6056dd35 fixes most performance issues with `Byte.v` (I'm no longer too impatient to wait for them to compile), but `Field_theory.v` still runs out of memory. It seems like this occurs during `Qed.` in `Pcond_Fnorm`.

**Comment by ionathanch** [comment]
d9b39228e3f6b99fe5f3b3fffcff9b6383470d12 is a workaround for the memory issue, mainly caused by constants having a *lot* of stage annotations (each `split` used within `Field_theory.v`, for instance, is annotated with 1064 stages). It does not give `Const`s any stage annotations if sized typing is off. The consequences of this and an example of its effects can be found [here](https://github.com/ionathanch/coq/blob/dev/test-suite/success/sized_typing.v#L283).

There's still the issue of whether the same should be done for `Var`s. In the kernel, `Var`s are implemented similarly to `Rel`s, but on the user side, they're used as `Let`s, similarly to `Definition`s (which are `Const`s). Semantically, `Let`s are similar to `let`s, but syntactically, they look at lot more like global definitions. In terms of memory, it's fine not to remove stage annotations for `Var`s.
